version: '3.8'

services:
  web:
    restart: always
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web:/usr/src/web
    ports:
      - 5000:5000